# Site settings
title: Product Design, Responsive Web Design, UX Design, Belfast Northern Ireland | Jordan Moore
email: jm@dawsonandrews.com
description: > # this means to ignore newlines until "baseurl:"
  Product designer, responsive web designer and UX designer in Belfast, Northern Ireland, specialising in user experience and accessible design
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://127.0.0.1:4000"
url: "http://jordanm.co.uk"
github: [metadata]
twitter_username: jordanmoore
github_username:  jordanmoore
paginate: 10
exclude: [node_modules]
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-haml
  - jekyll-livereload
  - octopress-minify-html

# Build settings
markdown: kramdown
sass:
  style: compressed
